"""Add has_started column to Game model

Revision ID: 706b19af7a62
Revises: 56ebf16e02ce
Create Date: 2024-10-03 15:37:54.367706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706b19af7a62'
down_revision = '56ebf16e02ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_started', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('has_started')

    # ### end Alembic commands ###
